<!DOCTYPE html>
<html lang="en">

<head>
    <base href="<?php echo BASE_URL ?>">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="css/style.css">
    <title>M & M</title>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg">
            <div class="container-fluid d-flex justify-content-between align-items-center">
                <a class="navbar-brand fw-bolder" href="home">M & M Desarrollo Inmobiliario</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false"
                    aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <div class="navbar-nav ms-auto">
                        <a class="nav-link fw-bolder" href="home">Inicio</a>
                        <a class="nav-link fw-bolder" href="listar">Asesores</a>
                        <a class="nav-link fw-bolder" href="listarVenta">Registro de Ventas</a>

                        <?php if (isset($_SESSION['USUARIO_VENDEDOR'])): ?>
                        <span class="navbar-text"><?= htmlspecialchars($_SESSION['USUARIO_VENDEDOR']) ?></span>
                        <!-- Display the user's email -->
                        <a class="nav-link fw-bolder" href="logout">Logout</a>
                        <?php else: ?>
                        <a class="nav-link fw-bolder" href="login">Login</a>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        </nav>
    </header>