<!DOCTYPE html>
<html lang="en">
<head>
    <base href="<?php echo BASE_URL ?>">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="css/style.css">
   
    <title>M & M</title>
</head>
<body>
<header>
<nav class="navbar navbar-expand-lg">
  <div class="container-fluid d-flex justify-content-between align-items-center">
    <!-- Logo con margen a la izquierda para ajustarlo hacia la izquierda -->
    <a class="navbar-brand fw-bolder" href="home">M & M Desarrollo Inmobiliario</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <!-- Enlaces alineados a la derecha con un margen a la derecha para un poco de espacio -->
      <div class="navbar-nav ms-auto">
        <a class="nav-link fw-bolder" aria-current="" href="home">Inicio</a>
        <a class="nav-link fw-bolder" href="listar">Vendedores</a>
        <a class="nav-link fw-bolder" href="listarVenta">Venta</a>
        <a class="nav-link fw-bolder" href="">Login</a>

      </div>
    </div>
  </div>
</nav>


</header>
   