<?php require_once 'app/templates/layout/header.phtml'; ?>
<div class="container my-4">
    <h1 class="text-light text-center mb-4">Ítems en la Categoría</h1>

    <?php if (!empty($items)): ?>
        <div class="card">
            <div class="card-body">
                <ul class="list-group">
                    <?php foreach ($items as $item): ?>
                        <li class="list-group-item bg-dark text-light">
                            <div class="d-flex justify-content-between align-items-center">
                                <div>
                                    <strong>Inmueble:</strong> <?= $item->inmueble ?><br>
                                    <strong>Fecha de venta:</strong> <?= date('d/m/Y', strtotime($item->fecha_venta)) ?><br><!--La función strtotime() convierte la fecha en un valor de tiempo Unix (una marca de tiempo), lo cual es necesario para formatearla correctamente.-->
                                    <strong>Precio:</strong> $<?= $item->precio ?><br>
                                    <strong>Vendedor:</strong> <?= $item->Id_vendedor ?>
                                </div>
                
                            </div>
                        </li>
                    <?php endforeach; ?>
                </ul>
                <br>
                <a href="<?= 'categorias/'; ?>" class="btn btn-primary">Volver a Categorías</a>
            </div>
        </div>
    <?php else: ?>
        <div class="alert alert-warning text-center mt-4">
            No hay ítems disponibles en esta categoría.
        </div>
    <?php endif; ?>
</div>

<?php require_once 'app/templates/layout/footer.phtml'; ?>
