<?php require_once 'app/templates/layout/header.phtml'; ?>

<body class="d-flex justify-content-center align-items-center vh-100 bg-light">
    <div class="text-center p-5 bg-white shadow rounded">
        <h1 class="text-danger">Error</h1>
        <p class="lead"><?= $message ?></p>
        <a href="home" class="btn btn-primary">Volver al inicio</a>
    </div>

<?php require_once 'app/templates/layout/footer.phtml'; ?>