
<form action="nueva" method="POST" class="bg-dark rounded">
    <!-- Campo para ingresar la URL de la foto -->
    <div>
        <label for="image" class="form-label text-light">URL de la Foto</label>
        <input type="url" name="image" id="image" class="form-control" placeholder="http://example.com/imagen.jpg"
            required>
    </div>
    <div>
        <label for="inmueble" class="form-label text-light">Inmueble</label>
        <input type="text" name="inmueble" id="inmueble" class="form-control" required>
    </div>
    <div>
        <label for="date" class="form-label text-light">Fecha</label>
        <input type="date" name="date" id="date" class="form-control" required>
    </div>
    <div>
        <label for="price" class="form-label text-light">Precio</label>
        <input type="number" name="price" id="price" class="form-control" step="0.01" required>
    </div>

    <label for="id_vendedor"></label>
    <select id="id_vendedor" name="id_vendedor" required>
        <option value="">Selecciona un vendedor</option>
        <?php if (!empty($sellers)): ?>
        <?php foreach ($sellers as $seller): ?>
        <option value="<?= $seller->id_vendedor; ?>">
            <?= $seller->Nombre . ' ' . $seller->Apellido; ?>
        </option>
        <?php endforeach; ?>
        <?php endif; ?>
    </select>


    <button type="submit" class="btn btn-primary">Agregar Venta</button>
</form>
