<?php require_once 'app/templates/layout/header.phtml'; ?>
<div class="container mt-5">
    <h1 class="text-center text-light">Editar Venta</h1>
    <form method="POST" action="editar/<?= htmlspecialchars($sale->id_venta) ?>"><!-- htmlsp..convierte caracteres especiales en sus equivalentes de entidades HTML.-->
        <div class="mb-3">
            <label for="image" class="imagen form-label text-light">URL de la Foto</label>
            <input type="url" class="form-control" name="image" id="image"
                value="<?= htmlspecialchars($sale->foto_url) ?>" placeholder="http://example.com/imagen.jpg">
        </div>
        <input type="hidden" name="id_venta" value="<?= htmlspecialchars($sale->id) ?>">
        <div class="mb-3">
            <label for="inmueble" class="form-label text-light">Inmueble</label>
            <input type="text" class="form-control" name="inmueble" id="inmueble"
                value="<?= htmlspecialchars($sale->inmueble) ?>" required>
        </div>
        <div class="mb-3">
            <label for="date" class="form-label text-light">Fecha de Venta</label>
            <input type="date" class="form-control" name="date" id="date"
                value="<?= htmlspecialchars($sale->fecha_venta) ?>" required>
        </div>
        <div class="mb-3">
            <label for="price" class="form-label text-light">Precio</label>
            <input type="number" class="form-control" name="price" id="price"
                value="<?= htmlspecialchars($sale->precio) ?>" required>
        </div>
        <!-- Select para elegir el vendedor -->
        <div class="mb-2">
            <label for="id_vendedor" class="form-label text-light">Asesor</label>
            <select name="id_vendedor" id="id_vendedor" class="form-control" required>
                <option value="">Seleccione un Asesor</option>
                <option value="1" <?php if ($sale->Id_vendedor == 1) echo 'selected'; ?>>Asesor 1</option>
                <option value="2" <?php if ($sale->Id_vendedor == 2) echo 'selected'; ?>>Asesor 2</option>
                <option value="3" <?php if ($sale->Id_vendedor == 3) echo 'selected'; ?>>Asesor 3</option>
                <option value="4" <?php if ($sale->Id_vendedor == 4) echo 'selected'; ?>>Asesor 4</option>
            </select>
        </div>
        <div class="text-center">
            <button type="submit" class="btn btn-primary text-light">Actualizar Venta</button>
            <a href= 'listarVenta'class="btn btn-secondary text-light">Cancelar</a>
        </div>
    </form>
</div>