
<form action="guardarVendedor" method="POST" class="bg-dark p-4 rounded">

    <div class="mb-2">
        <label for="name" class="form-label text-light">Nombre</label>
        <input type="text" name="name" id="name" class="form-control" required>
    </div>
    <div class="mb-2">
        <label for="firstName" class="form-label text-light">Apellido</label>
        <input type="text" name="firstName" id="firstName" class="form-control" required>
    </div>
    <div class="mb-2">
        <label for="telephone" class="form-label text-light">Telefono</label>
        <input type="text" name="telephone" id="telephone" class="form-control" required>
    </div>
    <div class="mb-2">
        <label for="email" class="form-label text-light">Email</label>
        <input type="text" name="email" id="email" class="form-control" required>
    </div>

    <button type="submit" class="btn btn-primary">Agregar Vendedor</button>
</form>
