<?php require_once 'app/templates/layout/header.phtml'; ?>
 
 <?php require_once 'app/templates/form_agregar_venta.phtml'; ?>

<div class="container d-flex justify-content-center align-items-center" style="min-height: 100vh;">
    <div class="row">
        
        <div class="col-12">
       
            <h1 class="text-center text-light">Lista de Inmuebles en Venta</h1>
            <p class="text-center text-light">Total de inmuebles: <?= $count ?></p>
            <ul class="list-group">
                
                <?php foreach ($sales as $sale): ?>
                    <li class="list-group-item bg-dark text-light d-flex justify-content-between align-items-center">
                        <div>
                            <a href="'venta' . $sale->id_venta ?>" class="text-decoration-none text-light">
                                <h5 class="mb-1">Inmueble: <?= $sale->inmueble ?></h5>
                                <p class="mb-1">Precio: $<?=$sale->precio ?></p>
                                <a href="<?=  'categorias/' ?>" class="badge 
                                    <?php
                                    // Añadir clase de estilo según la categoría
                                    if (isset($sale->categoria)) {
                                        echo ($sale->categoria === 'Alto') ? 'bg-danger' : (($sale->categoria === 'Medio') ? 'bg-warning' : 'bg-success');
                                    } else {
                                        echo 'bg-secondary';
                                    }
                                    ?>
                                    text-light" style="cursor: pointer;">
                                    <?= isset($sale->categoria) ? $sale->categoria : 'Sin categoría' ?>
                                </a>
                            </a>
                        </div>
                        <div>
                            <a href="<?= 'venta/' . $sale->id_venta ?>" class="btn btn-info btn-sm" role="button">
                                Ver Detalle
                            </a>
                            <a href="editar/<?= $sale->id_venta ?>" class="btn btn-warning btn-sm" role="button">Editar</a>

                            <a href="eliminar/<?= $sale->id_venta ?>" type="button" class='btn btn-danger btn-sm ml-auto'>Borrar</a>

                        </div>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
</div>

<?php require_once 'app/templates/layout/footer.phtml'; ?>