<?php require_once 'app/templates/layout/header.phtml'; ?>
<?php require_once 'app/templates/form_agregar_vendedor.phtml'; ?>

<div class="container d-flex justify-content-center align-items-center" style="min-height: 100vh;">
    <div class="row">
        <div class="col-12 text-center">
            <h1 class="text-center text-light">Lista de Vendedores</h1>
            <p class="text-center text-light">Total de vendedores: <?= $count ?></p>

            <ul class="list-group">
                <?php foreach ($sellers as $seller): ?>
                <li class="list-group-item bg-dark text-light">
                    <a href="<?= BASE_URL . 'vendedor/' . $seller->id_vendedor ?>"
                        class="text-decoration-none text-light d-flex justify-content-between align-items-center">
                        <div>
                            <strong>Nombre:</strong> <?= $seller->Nombre ?> <br>
                            <strong>Apellido:</strong> <?= $seller->Apellido ?>
                        </div>
                        <span class="badge bg-primary">Info</span>
                    </a>
                    <div>

                        <!-- Mostrar los botones Editar y Borrar solo si el usuario es administrador -->
                        <?php if (isset($_SESSION['ROL_VENDEDOR']) && $_SESSION['ROL_VENDEDOR'] === 'admin'): ?>
                        <a href="editarVendedor/<?= $seller->id_vendedor ?>" class="btn btn-warning btn-sm"
                            role="button">Editar</a>
                        <a href="eliminarVendedor/<?= $seller->id_vendedor ?>" type="button"
                            class="btn btn-danger btn-sm ml-auto">Borrar</a>
                        <?php endif; ?>
                    </div>
                </li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
</div>

<?php require_once 'app/templates/layout/footer.phtml'; ?>