<?php require_once 'app/templates/layout/header.phtml'; ?>

<?php if (isset($sale)): ?>
<div class="container d-flex justify-content-center align-items-center">
    <div class="row">
        <div class="col-12 text-center">
            <h1 class="text-center text-light">Detalles de la Venta</h1>
            <ul class="detail list-group">
                <li class="list-group-item bg-dark text-light">Inmueble: <?= htmlspecialchars($sale->inmueble, ENT_QUOTES, 'UTF-8') ?></li>
                <li class="list-group-item bg-dark text-light">Fecha de Venta: <?= htmlspecialchars($sale->fecha_venta, ENT_QUOTES, 'UTF-8') ?></li>
                <li class="list-group-item bg-dark text-light">Precio: <?= htmlspecialchars($sale->precio, ENT_QUOTES, 'UTF-8') ?></li>
                <li class="list-group-item bg-dark text-light">Asesor: <?= htmlspecialchars($sale->id_vendedor, ENT_QUOTES, 'UTF-8') ?></li>

                <!-- Muestra la imagen en lugar de la URL -->
                <li class="list-group-item bg-dark text-light">
                    Imagen: <br>
                    <img class="imagen" src="<?= htmlspecialchars($sale->foto_url, ENT_QUOTES, 'UTF-8') ?>" alt="Imagen del inmueble">
                </li>
            </ul>

            <br>
            <a href="<?= 'listarVenta/'; ?>" class="btn btn-primary">Volver a Ventas</a>
        </div>
    </div>
</div>
<?php else: ?>
<div class="container">
    <h2 class="text-light">No se encontró información de la venta.</h2>
    <a href="<?= 'listarVenta/';?>" class="btn btn-primary">Volver a Ventas</a>
</div>
<?php endif; ?>

<?php require_once 'app/templates/layout/footer.phtml'; ?>